name: IPA Builder

on:
  workflow_dispatch:

jobs:
  build-ipa:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.8'
          
      - name: Get dependencies
        run: flutter pub get
        
      - name: Build IPA
        run: flutter build ios --release --no-codesign
        
      - name: Collect IPA artifacts
        uses: actions/upload-artifact@v2
        with:
          name: release-ipa
          path: build/ios/iphoneos/
          
